language: cpp
sudo: true
branches:
    only:
        - master
matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
          - MATRIX_EVAL= "brew update && brew install gcc && CC=gcc-8 && CXX=g++-8"
    - os: linux

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test

before_install:
    - bash ./scripts/build_travis.sh
    - pip install --user cpp-coveralls
    - eval "${MATRIX_EVAL}"

install:       
    - hash -r
    - echo "Now try to build the module"
    - mkdir build 
    - cd build
    - cmake -DCOVERAGE=1 ..
    - make all
script:
    - ./hello
after_success:
    # - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"
