language: cpp
sudo: true

matrix:
  include:
    - os: osx
      env:
          # - MATRIX_EVAL= "brew update && brew install gcc && CC=/usr/local/gcc-8 && CXX=/usr/local/g++-8"

    - os: linux

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test

before_install:
    # - bash ./scripts/build_travis.sh
    # - pip install --user cpp-coveralls
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
install:       
    - hash -r
    - echo "Now try to build the module"
    - mkdir build 
    - cd build
    - cmake -DCOVERAGE=1 ..
    - make all
script:
    - ./hello
after_success:
    # - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"
